// Module2_FrontendDev_Hands_on_7-10_Kaviya_Dharshini_D/student-portal-angular/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

}
<header>
  <h1>Student Portal</h1>

  <nav>
    <a href="#">Home</a> |
    <a href="#">Courses</a> |
    <a href="#">Profile</a>
  </nav>
</header>

// Module2_FrontDev_Harini.T/hands_on_5/student-portal-react/src/components/Header.jsx
function Header({ siteName, enrolledCount }) {
  return (
    <header>
      <h1>{siteName}</h1>

      <nav>
        <a href="#">Home</a>
        <a href="#">Courses</a>
        <a href="#">Profile</a>
      </nav>

      <h3>Enrolled: {enrolledCount}</h3>
    </header>
  );
}

export default Header;
