// Module2_FrontDev_Harini.T/hands_on_6/student-portal-react/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {

  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header>

      <h1>Student Portal</h1>

      <nav>

        <Link to="/">Home</Link>

        <Link to="/courses">Courses</Link>

        <Link to="/profile">Profile</Link>

      </nav>

      <h3>Enrolled: {enrolledCourses.length}</h3>

    </header>
  );

}

export default Header;

// Module2_FrontendDev_Hands_on_7-10_Kaviya_Dharshini_D/Module2_FrontendDev_Hands_on_7-10_Harini.T/student-portal-vue/src/components/Header.vue
<template>
  <header class="header">
    <h1>Student Portal</h1>

    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">
        Profile ({{ store.enrolledCourses.length }})
      </RouterLink>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
.header {
  background: #42b983;
  color: white;
  padding: 16px 24px;

  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header h1 {
  margin: 0;
}

nav {
  display: flex;
  gap: 20px;
}

nav a {
  color: white;
  text-decoration: none;
  font-weight: bold;
}

.router-link-active {
  text-decoration: underline;
}
</style>
